### ISSUE TITLE
Required scopes for accessToken/refreshToken?

### ISSUE THREAD

**Issue by DanMittendorf** [alexa-samples/code-sample-nodejs-automatic-catalog-update#1]
What are the required scopes of the accessToken/refreshToken for this sample code to run properly? I've tried "alexa::ask:catalogs:readwrite" but this doesn't seem to be enough as the Script won't execute successfully.

`PS C:\Users\x\CatalogUpdater\code-sample-nodejs-automatic-catalog-update> node index.js
Update in progress, retrying in 2000 milliseconds...
{"lastUpdateRequest":{"errors":[],"status":"SUCCEEDED","version":"860"}}
Error when trying to create export for skill Error [ServiceError]: The auth token is invalid/expired or doesn&#39;t have access to the resource.
    at SkillManagementServiceClient.<anonymous> (C:\Users\x\CatalogUpdater\code-sample-nodejs-automatic-catalog-update\node_modules\ask-sdk-model-runtime\dist\index.js:335:31)
    at step (C:\Users\x\CatalogUpdater\code-sample-nodejs-automatic-catalog-update\node_modules\ask-sdk-model-runtime\dist\index.js:58:23)
    at Object.next (C:\Users\x\CatalogUpdater\code-sample-nodejs-automatic-catalog-update\node_modules\ask-sdk-model-runtime\dist\index.js:39:53)
    at fulfilled (C:\Users\x\CatalogUpdater\code-sample-nodejs-automatic-catalog-update\node_modules\ask-sdk-model-runtime\dist\index.js:30:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  statusCode: 401,
  headers: [
    { key: 'content-type', value: 'application/json' },
    { key: 'content-length', value: '55' },
    { key: 'connection', value: 'close' },
    { key: 'server', value: 'Server' },
    { key: 'date', value: 'Wed, 09 Aug 2023 12:23:03 GMT' },
    { key: 'x-amz-rid', value: '9AWZDXEXTDNM9E3FPC33' },
    {
      key: 'x-amzn-requestid',
      value: 'c9f0aee0-c7df-473c-9c5d-c19d091db704'
    },
    { key: 'x-amz-date', value: 'Wed, 09 Aug 2023 12:23:03 GMT' },
    {
      key: 'www-authenticate',
      value: 'Bearer realm="Login with Amazon"'
    },
    { key: 'vary', value: 'Content-Type,Accept-Encoding,User-Agent' },
    {
      key: 'strict-transport-security',
      value: 'max-age=47474747; includeSubDomains; preload'
    },
    { key: 'x-cache', value: 'Error from cloudfront' },
    {
      key: 'via',
      value: '1.1 5db4f6b1c04035a37ba6548e89b362be.cloudfront.net (CloudFront)'
    },
    { key: 'x-amz-cf-pop', value: 'DUS51-P2' },
    {
      key: 'x-amz-cf-id',
      value: 'MjtDcgSWYh8UGelyfNtscIXodCWO2cbiLvpIJfaPBnIStUoQ9REryg=='
    }
  ],
  response: { message: 'User has not consented to this operation.' }
}
Error when creating exporting and polling for status Error: Error when trying to create export for skill
    at createExport (C:\Users\x\CatalogUpdater\code-sample-nodejs-automatic-catalog-update\index.js:248:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async createExportAndPollTillCompletion (C:\Users\x\CatalogUpdater\code-sample-nodejs-automatic-catalog-update\index.js:232:24)
    at async getSkillPackageAndUpdateCatalogVersion (C:\Users\x\CatalogUpdater\code-sample-nodejs-automatic-catalog-update\index.js:219:34)
    at async runInteractionModelUpdateWorkflow (C:\Users\x\CatalogUpdater\code-sample-nodejs-automatic-catalog-update\index.js:195:7) {`

**Comment by DanMittendorf** [comment]
To answer this one: minimum scope is: `alexa::ask:skills:readwrite`

I'm going with `alexa::ask:catalogs:readwrite alexa::ask:skills:readwrite`

**Comment by aszk** [comment]
@DanMittendorf Thank you for your question. I will work on updating readme file. This is a great question.

**Comment by aszk** [comment]
https://github.com/alexa-samples/code-sample-nodejs-automatic-catalog-update/pull/3
Merged.
